### ISSUE TITLE
DATE function not working 

### ISSUE THREAD

**Issue by hjkwon0609** [AlaSQL/alasql#1627]
the DATE function is not working as expected

```
> alasql('CREATE TABLE t (id BIGINT, dt DATE)')
1
> alasql('INSERT INTO t (1, NOW())')
1
> alasql('INSERT INTO t (1, "2022-01-30 01:00:00")')
1
> alasql('SELECT * FROM t')
[
  { id: 1, dt: '2023-01-30 15:22:41.470' },
  { id: 1, dt: '2022-01-30 01:00:00' }
]
```
in general, timestamp / date objects don't work as expected (we've overridden function slike NOW, DATE_ADD etc for this)

however `DATE` itself seems to not throw an error but overriding also doesn't work..
```
> alasql('SELECT DATE(dt) FROM t')                             
[                                                        
  { 'DATE(dt)': 2023-01-30T06:22:41.470Z },                      
  { 'DATE(dt)': 2022-01-29T16:00:00.000Z }
]                                       
```

I've tried overriding `DATE` for this but this throws a confusing error

```
> const alasql = require('alasql');
undefined
> const moment = require('moment');
undefined
> alasql('CREATE TABLE t (id BIGINT, dt DATE)')
1
> const DATE_FORMAT = 'YYYY-MM-DD';
undefined
> alasql.fn.DATE = (dt) => moment(dt).format(DATE_FORMAT);
[Function (anonymous)]
> alasql.exec('INSERT INTO t (id, dt) values (1, "2022-01-30 01:00:00")')
Uncaught ReferenceError: DATE is not defined
    at yy.Insert.eval (eval at yy.Insert.compile (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:14433:18), <anonymous>:3:67)
    at statement (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:14493:14)
    at Function.alasql.dexec (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:4682:11)
    at Function.alasql.exec (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:4664:17)
```
(consistent regardless of whether DATE is overriden before the DDL or after)
```
> const alasql = require('alasql');
undefined
> const moment = require('moment');
undefined
> const DATE_FORMAT = 'YYYY-MM-DD';
undefined
> alasql.fn.DATE = (dt) => moment(dt).format(DATE_FORMAT);
[Function (anonymous)]
> alasql('CREATE TABLE t (id BIGINT, dt DATE)')
1
> alasql.exec('INSERT INTO t (id, dt) values (1, "2022-01-30 01:00:00")')
Uncaught ReferenceError: DATE is not defined
    at yy.Insert.eval (eval at yy.Insert.compile (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:14433:18), <anonymous>:3:67)
    at statement (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:14493:14)
    at Function.alasql.dexec (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:4711:28)
    at Function.alasql.exec (/home/mark/work/gopax/node_modules/alasql/dist/alasql.fs.js:4664:17)
```

**Comment by mathiasrw** [comment]
> general, timestamp / date objects don't work as expected (we've overridden function slike NOW, DATE_ADD etc for this)

Interesting. Do you mind sharing the functions so we can improve this for the community?

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1063454/215460653-5d0bb892-53e4-4165-ac88-166790b3bc80.png">
The problem is the time part of the field as its a date - right?

**Comment by hjkwon0609** [comment]
> > general, timestamp / date objects don't work as expected (we've overridden function slike NOW, DATE_ADD etc for this)
> 
> Interesting. Do you mind sharing the functions so we can improve this for the community?
> 

I'm currently using alasql for semi-unit testing sql queries so I've only fixed it to the point that it works for us

```
const DATE_FORMAT = 'YYYY-MM-DD';
const DATE_TIME_FORMAT = `${DATE_FORMAT} HH:mm:ss`;

alasql.fn.CURRENT_TIMESTAMP = alasql.fn.NOW = () => moment()
  .utc()
  .format(DATE_TIME_FORMAT);
alasql.fn.DATE_SUB = (dt, interval) => moment(dt)
  .subtract(interval, 'milliseconds')
  .format(DATE_TIME_FORMAT);
alasql.fn.DATE_ADD = (dt, interval) => moment(dt)
  .add(interval, 'milliseconds')
  .format(DATE_TIME_FORMAT);
alasql.fn.UNIX_TIMESTAMP = (dt) => moment(dt, DATE_TIME_FORMAT).unix();
```
the overrides also use `moment` which I'm not sure alasql would want just for datetime functionality

**Comment by mathiasrw** [comment]
Thanks for sharing. 

Do you remember why the build in function was not working for you?

**Comment by mathiasrw** [comment]
> in sql, these two should return as the same data type but it turns out the returned data types are different

I see. Yes. Hmm. This is a good point. Ill make sure to align this. This is not good.

**Comment by Mohit269** [comment]
Hey there, i'm interested in this issue will you please assign this to me.

**Comment by mathiasrw** [comment]
Sure!

**Comment by mathiasrw** [comment]
Any luck @Mohit269 ?

**Comment by mathiasrw** [comment]
Note 

| Database | Output | 
|---|---
| MySQL | `2023-06-09 15:11:18` | |
| PostgreSQL | `2023-06-09T15:11:18.000Z` | |
| Microsoft SQL Server | `2023-06-09 15:11:18.123` | |
| Oracle | `2023-06-09 15:11:18` | |
| IBM DB2 | `2023-06-09 15:11:18.123` | |
| SQLite | `2023-06-09 15:13:13` |

**Comment by mathiasrw** [comment]
Yes. This is absolutely broken. We need to make a series of breaking changes. 

<img width="558" alt="image" src="https://github.com/AlaSQL/alasql/assets/1063454/7041c614-fc24-459f-8c40-e11d976846f9">

We need a formatter that you can configure for all the date options - including the option to use the date object - (like some of them got now)

**Comment by mathiasrw** [comment]
We will be planning for a breaking change where all date data returned are formatted the same way

@agershun and I have decided that we will default to the string format and provide an option get all raw dates information as a javascript object.

**Comment by Shibn2** [comment]
If the issue is still not fixed, I 'd like to contribute. @mathiasrw

**Comment by paulrutter** [comment]
Do note that recently, the `alasql.options.dateAsString` option was introduced (defaults to true for backwards compatibility).
When set to false, both `NOW` and `GETDATE` will just return a Date object instead of a string formatted Date.

**Comment by mathiasrw** [comment]
@paulrutter Thank you for pointing this out. I have updated https://github.com/AlaSQL/alasql/wiki/Alasql-Options

@Shibn2 any progress on this?

**Comment by mathewalexKerala** [comment]
I want to work on this issue , if nobody is doing it

**Comment by mathiasrw** [comment]
@mathewalexKerala Please!

**Comment by paulrutter** [comment]
@mathiasrw @mathewalexKerala can you please make sure that when using alasql.options.dateAsString=false, it remains to work as is?
We use dates a lot with that setting, and have no issues at all (as long as JS dates are used instead of string values).

**Comment by mathiasrw** [comment]
Its a good point. We should make sure to not change any of the old tests in order to get the new things working.

**Comment by mathewalexKerala** [comment]
> @mathiasrw @mathewalexKerala can you please make sure that when using alasql.options.dateAsString=false, it remains to work as is? We use dates a lot with that setting, and have no issues at all (as long as JS dates are used instead of string values).

sure

**Comment by mathewalexKerala** [comment]
@paulrutter  @mathiasrw  should I fix both the browser side and server side code ?

**Comment by paulrutter** [comment]
That is the same code, as it's javascript either run in the browser or in nodejs. Thus, both environments will work if you have a fix for the issue at hand.
@mathewalexKerala
