### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by an0sv** [AlaSQL/alasql#1671]
alasql("SELECT SUM(cnt) AS total FROM ?", [[]])
-----------------------------------------^
Expecting 'LITERAL', 'BRALITERAL', 'NUMBER', 'STRING', 'NSTRING', got 'TOTAL'
    at Ei.parseError (alasql.min.js:32:246120)
    at Si.parse (alasql.min.js:32:241538)
    at e.parse (alasql.min.js:32:271321)
    at e.dexec (alasql.min.js:32:272931)
    at e.exec (alasql.min.js:32:272685)
    at e (alasql.min.js:32:919)
    at T (app.js?{bundletime}:1:8299)
    at app.js?{bundletime}:1:15135

From what I can see in the docs total should not be a reserved word, or?

The alasql version I'm using is 3.0.0

**Comment by mathiasrw** [comment]
Yes. Total is a reserved word. Please use backticks to encapsulate `Total`
