### ISSUE TITLE
PIVOT()

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#490]
There is a request to add `PIVOT` functionality to AlaSQL.

**Comment by mathiasrw** [comment]
Sounds great!

There is some talks about `PIVOT()` here: https://github.com/agershun/alasql/issues/287

**Comment by agershun** [comment]
Yes, I just received request, may be this help us to finish with it :)

**Comment by mathiasrw** [comment]
![lets do it](http://www.internetmonk.com/wp-content/uploads/lets-do-this-meme-no-cuss-words.jpg)

**Comment by agershun** [comment]
I did this.

Unfortunately, it works still does not comply with standard T-SQL syntax (now AlaSQL processes data to pivot after SELECT function, but it should be oerformed immediatly after FROM part). But it works. PIVOT and UNPIVOT.

Here are the examples for PIVOT:
```sql

		select * from DailyIncome
		pivot (max (IncomeAmount) for IncomeDay in ([MON],[TUE],[WED],[THU],[FRI],[SAT],[SUN])) as MaxIncomePerDay
		where VendorId in ('SPIKE')
```
And UNPIVOT:
```sql
    SELECT VendorID, Emp1, Emp2, Emp3, Emp4, Emp5
       FROM pvt
    UNPIVOT
       (Orders FOR Employee IN 
          (Emp1, Emp2, Emp3, Emp4, Emp5)
    )AS unpvt;
```
See [text359.js](https://github.com/agershun/alasql/blob/develop/test/test359.js) and [text380.js](https://github.com/agershun/alasql/blob/develop/test/test380.js) for other examples.

**Comment by mathiasrw** [comment]
Closed per request from #628

**Comment by keyscores** [comment]
@mathiasrw I'm working through the tests above. I see they work, but I don't see any documentation. I'm trying to work through the 'simple' pivot, with a JSON datasource. See below:

```
  var data = [ { VendorId: 'SPIKE', IncomeDay: 'FRI', IncomeAmount: 100 },
  { VendorId: 'SPIKE', IncomeDay: 'MON', IncomeAmount: 300 },
  { VendorId: 'FREDS', IncomeDay: 'SUN', IncomeAmount: 400 },
  { VendorId: 'SPIKE', IncomeDay: 'WED', IncomeAmount: 500 },
  { VendorId: 'SPIKE', IncomeDay: 'TUE', IncomeAmount: 200 },
  { VendorId: 'JOHNS', IncomeDay: 'WED', IncomeAmount: 900 },
  { VendorId: 'SPIKE', IncomeDay: 'FRI', IncomeAmount: 100 },
  { VendorId: 'JOHNS', IncomeDay: 'MON', IncomeAmount: 300 },
  { VendorId: 'SPIKE', IncomeDay: 'SUN', IncomeAmount: 400 },
  { VendorId: 'JOHNS', IncomeDay: 'FRI', IncomeAmount: 300 },
  { VendorId: 'FREDS', IncomeDay: 'TUE', IncomeAmount: 500 },
  { VendorId: 'FREDS', IncomeDay: 'TUE', IncomeAmount: 200 },
  { VendorId: 'SPIKE', IncomeDay: 'MON', IncomeAmount: 900 },
  { VendorId: 'FREDS', IncomeDay: 'FRI', IncomeAmount: 900 },
  { VendorId: 'FREDS', IncomeDay: 'MON', IncomeAmount: 500 },
  { VendorId: 'JOHNS', IncomeDay: 'SUN', IncomeAmount: 600 },
  { VendorId: 'SPIKE', IncomeDay: 'FRI', IncomeAmount: 300 },
  { VendorId: 'SPIKE', IncomeDay: 'WED', IncomeAmount: 500 },
  { VendorId: 'SPIKE', IncomeDay: 'FRI', IncomeAmount: 300 },
  { VendorId: 'JOHNS', IncomeDay: 'THU', IncomeAmount: 800 },
  { VendorId: 'JOHNS', IncomeDay: 'SAT', IncomeAmount: 800 },
  { VendorId: 'SPIKE', IncomeDay: 'TUE', IncomeAmount: 100 },
  { VendorId: 'SPIKE', IncomeDay: 'THU', IncomeAmount: 300 },
  { VendorId: 'FREDS', IncomeDay: 'WED', IncomeAmount: 500 },
  { VendorId: 'SPIKE', IncomeDay: 'SAT', IncomeAmount: 100 },
  { VendorId: 'FREDS', IncomeDay: 'SAT', IncomeAmount: 500 },
  { VendorId: 'FREDS', IncomeDay: 'THU', IncomeAmount: 800 },
  { VendorId: 'JOHNS', IncomeDay: 'TUE', IncomeAmount: 600 } ]


  var res = alasql('select * from ? pivot (AVG(IncomeAmount) for IncomeDay)', [data])
```

returns 

`TypeError: Cannot set property 'columnid' of undefined
`

Might be a silly error I'm making. I think documentation with this case would be very helpful.

**Comment by mathiasrw** [comment]
Hi @keyscores 

You are not forgotten. I cant get my head around whats working and whats not. Im using http://sqlfiddle.com/#!3/7d09c/1 as example - but its not playing nice.

**Comment by keyscores** [comment]
I got the example above to work by studying another test you have. Try this: http://jsfiddle.net/auazvzpg/

However, I don't understand the [] syntax.
`  var res = alasql('select VendorId, IncomeDay, [IncomeAmount]  from ? pivot (AVG(IncomeAmount) for IncomeDay)', [data])
`

**Comment by mathiasrw** [comment]
Nice ! 

`[IncomeAmount]` is only needed if the column is a keyword - sp no need: http://jsfiddle.net/auazvzpg/1/

**Comment by keyscores** [comment]
Ok thanks, I had just copied the other test, I wasn't sure what the [] in the SELECT section was doing. Thanks again!

**Comment by iamvitali** [comment]
I'm also getting the `Uncaught (in promise) TypeError: Cannot set property 'columnid' of undefined` error message. :/

**Comment by BigsaveCory** [comment]
Also getting ```Cannot set property 'columnid'```.

**Comment by rg312** [comment]
Also facing the above issue. :(

**Comment by jdimmerman** [comment]
I am able to get this to work properly if I have explicit column references in the SELECT clause. You cannot `SELECT *` or you will get the error `TypeError: Cannot set property 'columnid' of undefined`

**Comment by MianAnwar** [comment]
Still facing the issue, 

```
ERROR:

TypeError: Cannot set properties of undefined (setting 'columnid')
    at alasql.min.js:119:10414
    at Array.forEach (<anonymous>)
    at ur.pivotfn (alasql.min.js:119:10372)
    at cr (alasql.min.js:49:4816)
    at lr (alasql.min.js:49:1206)
    at Object.eval [as datafn] (eval at <anonymous> (alasql.min.js:67:2732), <anonymous>:3:57)
    at alasql.min.js:49:692
    at Array.forEach (<anonymous>)
    at pi (alasql.min.js:49:652)
    at f (alasql.min.js:66:648)
 ```   
  
 Execute-Query: `SELECT b_n FROM ? PIVOT(COUNT(b_n) FOR b_n)`

**Comment by szsolutions** [comment]
I also get the error ‘Cannot set properties of undefined (setting “columnid”)’
Has anyone found a workaround?

**Comment by mathiasrw** [comment]
I added a test file for this issue in https://github.com/AlaSQL/alasql/commit/5217f44d4380516d07fa661345a0cc93ac402ba7,  but skipping for now until there is a fix.

**Comment by mathiasrw** [comment]
Fix released as part of v4.6.5
