### ISSUE TITLE
SyntaxError: Invalid Unicode escape sequence

### ISSUE THREAD

**Issue by vkupar** [AlaSQL/alasql#985]
I'm trying to open excel. It's working on Linux (Ubuntu), but not working on windows.

SyntaxError: Invalid Unicode escape sequence
    at C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:7419:20
    at Array.forEach (native)
    at yy.Select.compileFrom (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:7247:12)
    at yy.Select.compile (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:6833:22)
    at Function.alasql.dexec (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:4058:38)
    at Function.alasql.exec (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:4028:17)
    at alasql (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:120:18)
    at C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:4330:10
    at lib$es6$promise$$internal$$initializePromise (C:\Users\Test\Desktop\Test\server\node_modules\es6-promise\dist\es6-promise.js:366:9)
    at new lib$es6$promise$promise$$Promise (C:\Users\Test\Desktop\Test\server\node_modules\es6-promise\dist\es6-promise.js:657:9)
    at Function.alasql.promise (C:\Users\Test\Desktop\Test\server\node_modules\alasql\dist\alasql.js:4329:13)
    at WriteStream.writer.on.err (C:\Users\Test\Desktop\Test\server\controllers\v2\publicController.js:392:20)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:514:14)
    at afterWrite (_stream_writable.js:388:3)
    at onwrite (_stream_writable.js:378:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fs.js:2151:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:749:5)

OS: Windows 7
Node.js: v6.11.5
Alasql: 0.1.10

**Comment by mathiasrw** [comment]
Please provide the code to replicate this.

**Comment by vatex** [comment]
alasql.promise("select * from xlsx('" + filePath + "' ,{ headers:true }) where Text IS NOT NULL", []).then(function(doc) {
  console.log(doc);
}).catch(function(err) {
  // Error comes here
  console.log(err);
});

**Comment by mathiasrw** [comment]
Please provide an example file too
